version: '3.8'

services:
  nextjs-app:
    image: takumi/ocr-frontend
    container_name: ocr-frontend
    build:
      context: .
      dockerfile: src/Dockerfile 
    ports:
      - "3030:3000" 
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev 

